DROP TABLE IF EXISTS additives;
CREATE TABLE additives (
   SUBJECT_ID UNSIGNED SMALLINT NOT NULL ,
   ICUSTAY_ID UNSIGNED MEDIUMINT ,
   ORDERID UNSIGNED MEDIUMINT ,
   ITEMID UNSIGNED MEDIUMINT NOT NULL ,
   LABEL VARCHAR(256) NOT NULL ,
   IOITEMID UNSIGNED MEDIUMINT NOT NULL ,
   IOITEMLABEL VARCHAR(256) NOT NULL ,
   CHARTTIME VARCHAR(256) ,
   STARTTIME VARCHAR(256) ,
   ENDTIME VARCHAR(256) ,
   ELEMID UNSIGNED SMALLINT ,
   CGID SMALLINT NOT NULL ,
   CUID TINYINT NOT NULL ,
   VALUE VARCHAR(256) NOT NULL ,
   UOM VARCHAR(256) NOT NULL ,
   IOITEMVALUE VARCHAR(256) ,
   IOITEMUOM VARCHAR(256) ,
   SOURCE_FLG VARCHAR(256) NOT NULL ,
   ADDITIVESDATAID UNSIGNED MEDIUMINT NOT NULL )

